cse110-sp24-group9/CSE110-Project

admin/meetings/04262024-meeting_3.md

Meeting notes for third meeting

---

package-lock.json
package.json

added jest auto sense to project
fixes #10

added jest auto type sense for type completion

---

.github/workflows/jsdoc.yml
.jsdoc.json
package-lock.json
package.json
source/place_holder.js

fixes #50 
fixes #49 
fixes #48

Jsdoc auto bot

---

.github/workflows/jsdoc.yml

fixed a small issue in the initial pr

modification to avoid secrets being shared

---

.github/workflows/jsdoc.yml

fixed npm mistake

---

.jsdoc.json
package-lock.json
package.json

changed theme should fix major issue

changed template to something more modern to escape taffy requirement

---

.github/workflows/jsdoc.yml

Jsdoc bot revision

---

admin/meetings/Frontend_Design/0510-meeting-1.md

design and frontend meeting 510

---

.github/workflows/jsdoc.yml

just uses default want to see what happens

use default user settings

---

source/place_holder.js

testing to see bot commit message and user

testing purposes

---

package-lock.json
package.json
source/components/CalendarItem.js
source/pages/Calendar.html
source/styles/Calendar.css

Calendar component

---

source/prototype/eventList/eventList.html
source/prototype/eventList/eventList.js
source/prototype/eventList/style.css

update eventlist feature

---

specs/static/EventList/events.html
specs/static/EventList/style.css

Import Static HTML and CSS for Event List

---

specs/static/JournalEntries/Assets/draft-svgrepo-com.svg
specs/static/JournalEntries/Assets/filter-svgrepo-com.svg
specs/static/JournalEntries/index.html
specs/static/JournalEntries/style.css

Import Static HTML and CSS for Journal Entry List

---

specs/static/TaskList/newindex.html
specs/static/TaskList/newstyle.css

Import Static HTML and CSS for Task List

---

source/components/CalendarItem.js
source/pages/Calendar.html

Adds better testing compatability for the calendar by adding a hydration event

testing compat for caledar compoent

---

admin/meetings/052324-retrospective.md

finished the second retrospective using the sailboat method

finished retrospective

---

admin/meetings/052524-sprint-2-review.md

sprint review notes

---

specs/static/Canvas/new-tag-form.html
specs/static/EventList/new-event-form.html

forms for new event and new tag.

Static form files

---

source/components/Canvas.js
source/components/Event-list.js
source/pages/Event-list.html
source/pages/JournalApp.html
source/styles/Canvas.css
source/styles/Event-list.css
source/styles/JournalApp.css

add event list and form to the main page

Main page added event list

---

source/pages/JournalApp.html
source/styles/JournalApp.css
source/styles/lightmode/JournalApp.css

As title, still need to work on the sizing of calendar

Fix sizing for tool-bar and label-bar

---

source/styles/lightmode/JournalApp.css

As title, also change the code styling, add tabs, delete empty lines, etc

fix sizing for calendar

---

source/styles/lightmode/Calendar.css

fix bug: fade out from circle to square, now from circle to circle.

---

source/components/JournalApp.js
source/pages/JournalApp.html
source/styles/darkmode/JournalApp.css

the filter Button drop down has been created and styled.

FilterButton DropDown

---

source/components/Canvas.js
source/pages/JournalApp.html

As title, leave for backend team to finish

Update save button but not finished

---

source/styles/Event-list.css
source/styles/lightmode/Event-list.css

Fixes to -displayEvents and eventTitle

Event-List Styling Fixes

---

source/pages/JournalApp.html
source/styles/Canvas.css
source/styles/JournalApp.css
source/styles/JournalEntries.css
source/styles/darkmode/JournalApp.css
source/styles/lightmode/JournalApp.css
source/styles/task-list.css

Add changes to tags so that I can work on fetching them

---

source/pages/db-tester.html
source/scripts/db.js

Co-authored-by: Lance Tran <thelancetran@users.noreply.github.com>

Indexdb created and is functional

---

source/components/JournalEntries.js

Returns a list of Entry JSON objects to save to database

Implemented saveEntries() function

---

source/components/Event-list.js
source/components/Task-list.js
source/pages/task-list.html

Tasklist db

---

source/components/JournalEntries.js

added immutable reference

---

source/components/CalendarItem.js

Finished fetching the current date time for saving journals

---

admin/meetings/060824-sprint-3-review.md
admin/meetings/060924-retrospective.md

I wrote the retrospective 3 alongside my team

Recorded Retrospective 3

---

source/components/Canvas.js

Fixed issue with repetitive event listers on same page
